"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getActiveWorkspace, type WorkspaceRole } from "@/lib/auth/workspace";
import { resolveAppBaseUrl, sendInviteLink } from "@/lib/auth/invite-email";
import { logUsage } from "@/lib/usage/log";

const INVITABLE_ROLES: readonly WorkspaceRole[] = ["owner", "admin", "member"];

// ---------- helpers ---------------------------------------------------------

// Authoritative owner count via the admin client. Used as the gate that
// prevents the workspace from being orphaned (no one left to manage it).
async function countOwners(workspaceId: string): Promise<number> {
  const admin = createAdminClient();
  const { count } = await admin
    .from("workspace_memberships")
    .select("id", { count: "exact", head: true })
    .eq("workspace_id", workspaceId)
    .eq("role", "owner");
  return count ?? 0;
}

// ---------- invite ----------------------------------------------------------

export async function inviteMember(formData: FormData) {
  const started = Date.now();
  const { workspace, user, role } = await getActiveWorkspace("/settings/members");
  if (role !== "owner" && role !== "admin") {
    logUsage({
      event: "member.invite",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: "not_authorized",
    });
    return { error: "Only Admins and Owners can invite members." };
  }

  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  const requestedRole = String(formData.get("role") ?? "member") as WorkspaceRole;
  if (!email) return { error: "Email is required." };
  if (!INVITABLE_ROLES.includes(requestedRole)) {
    return { error: "Invalid role." };
  }
  if (requestedRole === "owner" && role !== "owner") {
    return { error: "Only Owners can invite another Owner." };
  }

  // 1. Create the workspace_invites row. The token is generated by the column
  //    default (32 random bytes, url-safe base64 — see
  //    supabase/migrations/0000_workspace_foundation.sql). We use the
  //    user-context client so RLS enforces "must be a member of this
  //    workspace" — the role gate above is belt and suspenders.
  const supabase = await createClient();
  const { data: invite, error: insertErr } = await supabase
    .from("workspace_invites")
    .insert({
      workspace_id: workspace.id,
      email,
      role: requestedRole,
      invited_by: user.id,
    })
    .select("token")
    .single();

  if (insertErr) {
    logUsage({
      event: "member.invite",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: insertErr.code ?? "insert_error",
      props: { role: requestedRole, duplicate: insertErr.code === "23505" },
    });
    if (insertErr.code === "23505") {
      return {
        error:
          "There's already a pending workspace invite for that email. Revoke it first to change their role.",
      };
    }
    return { error: insertErr.message };
  }

  // 2. Email the invite link. sendInviteLink encapsulates the
  //    inviteUserByEmail -> magic-link fallback shared with the deck-scoped
  //    guest invite (lib/auth/invite-email.ts), so both invite surfaces stay in
  //    sync. The invite row already exists and the link is copy-pasteable from
  //    the pending list, so a send failure surfaces a warning, never a rollback.
  //    The user clicks "Join Workspace" on /invite/{token} to create the
  //    membership — we don't create it here (that's their consent step).
  const send = await sendInviteLink(email, invite.token, {
    workspace_id: workspace.id,
    workspace_name: workspace.name,
    invited_role: requestedRole,
  });

  logUsage({
    event: "member.invite",
    surface: "action",
    user_id: user.id,
    workspace_id: workspace.id,
    status: "ok",
    duration_ms: Date.now() - started,
    props: { role: requestedRole, email_sent: send.emailed },
  });

  revalidatePath("/settings/members");
  return send.emailed
    ? { ok: true as const }
    : { ok: true as const, warning: send.warning };
}

// ---------- revoke pending invite ------------------------------------------

export async function revokeInvite(inviteId: string) {
  const started = Date.now();
  const { workspace, user, role } = await getActiveWorkspace("/settings/members");
  if (role !== "owner" && role !== "admin") {
    logUsage({
      event: "member.invite_revoke",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: "not_authorized",
      props: { invite_id: inviteId },
    });
    return { error: "Only Admins and Owners can revoke invites." };
  }

  // Scope to workspace-level invites only (deck_id is null). Deck-scoped guest
  // invites are managed from the deck's Share dialog (revokeGuestInvite), which
  // re-checks canvas_can_edit_deck — revoking one from here would let a
  // workspace admin cancel a deck editor's pending reviewer from the wrong
  // surface.
  const supabase = await createClient();
  const { error } = await supabase
    .from("workspace_invites")
    .delete()
    .eq("id", inviteId)
    .eq("workspace_id", workspace.id)
    .is("deck_id", null);
  if (error) {
    logUsage({
      event: "member.invite_revoke",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: error.code ?? "delete_error",
      props: { invite_id: inviteId },
    });
    return { error: error.message };
  }

  logUsage({
    event: "member.invite_revoke",
    surface: "action",
    user_id: user.id,
    workspace_id: workspace.id,
    status: "ok",
    duration_ms: Date.now() - started,
    props: { invite_id: inviteId },
  });

  revalidatePath("/settings/members");
  return { ok: true as const };
}

// ---------- resend invite email --------------------------------------------

export async function resendInvite(inviteId: string) {
  const started = Date.now();
  const { workspace, user, role } = await getActiveWorkspace("/settings/members");
  if (role !== "owner" && role !== "admin") {
    logUsage({
      event: "member.invite_resend",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: "not_authorized",
      props: { invite_id: inviteId },
    });
    return { error: "Only Admins and Owners can resend invites." };
  }

  const admin = createAdminClient();
  const { data: invite, error: lookupErr } = await admin
    .from("workspace_invites")
    .select("email, token, expires_at, accepted_at")
    .eq("id", inviteId)
    .eq("workspace_id", workspace.id)
    .maybeSingle();
  if (lookupErr || !invite) {
    logUsage({
      event: "member.invite_resend",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: "invite_not_found",
      props: { invite_id: inviteId },
    });
    return { error: "Invite not found." };
  }
  if (invite.accepted_at) {
    logUsage({
      event: "member.invite_resend",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: "already_accepted",
      props: { invite_id: inviteId },
    });
    return { error: "Invite already accepted." };
  }
  if (new Date(invite.expires_at) < new Date()) {
    logUsage({
      event: "member.invite_resend",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: "expired",
      props: { invite_id: inviteId },
    });
    return { error: "Invite expired. Revoke and re-invite." };
  }

  const baseUrl = await resolveAppBaseUrl();
  const redirectTo = `${baseUrl}/invite/${invite.token}`;

  const supabase = await createClient();
  const { error } = await supabase.auth.signInWithOtp({
    email: invite.email,
    options: {
      shouldCreateUser: false,
      emailRedirectTo: redirectTo,
    },
  });
  if (error) {
    logUsage({
      event: "member.invite_resend",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: "otp_failed",
      props: { invite_id: inviteId },
    });
    return { error: `Could not resend: ${error.message}` };
  }

  logUsage({
    event: "member.invite_resend",
    surface: "action",
    user_id: user.id,
    workspace_id: workspace.id,
    status: "ok",
    duration_ms: Date.now() - started,
    props: { invite_id: inviteId },
  });

  return { ok: true as const };
}

// ---------- change role ----------------------------------------------------

export async function changeRole(
  membershipId: string,
  newRole: WorkspaceRole,
) {
  const started = Date.now();
  const { workspace, user, role } = await getActiveWorkspace("/settings/members");
  const denied = (code: string) => {
    logUsage({
      event: "member.role_change",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: code,
      props: { membership_id: membershipId, new_role: newRole },
    });
  };
  if (role !== "owner" && role !== "admin") {
    denied("not_authorized");
    return { error: "Only Admins and Owners can change member roles." };
  }
  if (!INVITABLE_ROLES.includes(newRole)) {
    denied("invalid_role");
    return { error: "Invalid role." };
  }
  if (newRole === "owner" && role !== "owner") {
    denied("owner_promotion_blocked");
    return { error: "Only Owners can promote to Owner." };
  }

  const admin = createAdminClient();
  const { data: target, error: tErr } = await admin
    .from("workspace_memberships")
    .select("role, user_id")
    .eq("id", membershipId)
    .eq("workspace_id", workspace.id)
    .maybeSingle();
  if (tErr || !target) {
    logUsage({
      event: "member.role_change",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: tErr?.code ?? "member_not_found",
      props: { membership_id: membershipId, new_role: newRole },
    });
    return { error: tErr?.message ?? "Member not found." };
  }

  // Guests are deck-scoped outside reviewers (migration 0025): they reach a
  // deck only via canvas_deck_member and must never be promoted into a full
  // workspace role from the roster. INVITABLE_ROLES blocks 'guest' as a
  // DESTINATION, but nothing stopped a guest being the TARGET of a promote —
  // the read-only badge in MembersList is presentation, not a security
  // boundary. This is the authoritative guard.
  if (target.role === "guest") {
    denied("guest_not_promotable");
    return {
      error:
        "Guests are scoped to a single deck and can't be promoted here. Re-invite them as a workspace member instead.",
    };
  }

  // Admins can't touch Owner rows. Owners can touch anyone.
  if (target.role === "owner" && role !== "owner") {
    denied("owner_change_blocked");
    return { error: "Only Owners can change an Owner's role." };
  }

  // Prevent demoting the last Owner — would lock the workspace (no one to
  // manage members/billing).
  if (target.role === "owner" && newRole !== "owner") {
    const owners = await countOwners(workspace.id);
    if (owners <= 1) {
      denied("last_owner");
      return {
        error: "Can't demote the last Owner. Promote another Member to Owner first.",
      };
    }
  }

  const { data, error } = await admin
    .from("workspace_memberships")
    .update({ role: newRole })
    .eq("id", membershipId)
    .eq("workspace_id", workspace.id)
    .select("id");
  if (error) {
    logUsage({
      event: "member.role_change",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: error.code ?? "update_error",
      props: { membership_id: membershipId, new_role: newRole },
    });
    return { error: error.message };
  }
  if (!data || data.length === 0) {
    denied("rejected");
    return { error: "Role change rejected." };
  }

  logUsage({
    event: "member.role_change",
    surface: "action",
    user_id: user.id,
    workspace_id: workspace.id,
    status: "ok",
    duration_ms: Date.now() - started,
    props: {
      membership_id: membershipId,
      new_role: newRole,
      prev_role: target.role,
      self: target.user_id === user.id,
    },
  });

  revalidatePath("/settings/members");
  // Topbar shows the actor's role — refresh the dashboard too if it was self.
  if (target.user_id === user.id) revalidatePath("/canvases");
  return { ok: true as const };
}

// ---------- remove member --------------------------------------------------

export async function removeMember(membershipId: string) {
  const started = Date.now();
  const { workspace, user, role } = await getActiveWorkspace("/settings/members");
  const denied = (code: string) => {
    logUsage({
      event: "member.remove",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "denied",
      duration_ms: Date.now() - started,
      error_code: code,
      props: { membership_id: membershipId },
    });
  };
  if (role !== "owner" && role !== "admin") {
    denied("not_authorized");
    return { error: "Only Admins and Owners can remove members." };
  }

  const admin = createAdminClient();
  const { data: target, error: tErr } = await admin
    .from("workspace_memberships")
    .select("role, user_id")
    .eq("id", membershipId)
    .eq("workspace_id", workspace.id)
    .maybeSingle();
  if (tErr || !target) {
    logUsage({
      event: "member.remove",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: tErr?.code ?? "member_not_found",
      props: { membership_id: membershipId },
    });
    return { error: tErr?.message ?? "Member not found." };
  }

  // Admins can only remove Members. Owner action required to remove another
  // Admin or an Owner.
  if (role === "admin" && target.role !== "member") {
    denied("admin_cannot_remove_admin_or_owner");
    return { error: "Admins can only remove Members. Owner action required." };
  }

  if (target.role === "owner") {
    const owners = await countOwners(workspace.id);
    if (owners <= 1) {
      denied("last_owner");
      return {
        error: "Can't remove the last Owner. Promote another Member to Owner first.",
      };
    }
  }

  // UI hides the self-remove control, but a direct call would otherwise
  // succeed and orphan the actor's session.
  if (target.user_id === user.id) {
    denied("self_remove_blocked");
    return {
      error: "You can't remove yourself. Ask another Owner, or transfer Owner first.",
    };
  }

  const { data, error } = await admin
    .from("workspace_memberships")
    .delete()
    .eq("id", membershipId)
    .eq("workspace_id", workspace.id)
    .select("id");
  if (error) {
    logUsage({
      event: "member.remove",
      surface: "action",
      user_id: user.id,
      workspace_id: workspace.id,
      status: "error",
      duration_ms: Date.now() - started,
      error_code: error.code ?? "delete_error",
      props: { membership_id: membershipId },
    });
    return { error: error.message };
  }
  if (!data || data.length === 0) {
    denied("already_gone");
    return { error: "Member not removed (already gone?)." };
  }

  logUsage({
    event: "member.remove",
    surface: "action",
    user_id: user.id,
    workspace_id: workspace.id,
    status: "ok",
    duration_ms: Date.now() - started,
    props: {
      membership_id: membershipId,
      target_role: target.role,
    },
  });

  revalidatePath("/settings/members");
  return { ok: true as const };
}
