import { beforeAll, describe, expect, it } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import {
  ASSET_UPLOAD_MIMES,
  isAllowlistedFontUrl,
  parseDeckHtml,
} from "../src/lib/canvas/parser";

const fixturesDir = join(__dirname, "fixtures");

function readFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), "utf-8");
}

describe("parseDeckHtml — mini fixture", () => {
  const html = readFixture("mini-deck.html");
  const deck = parseDeckHtml(html);

  it("extracts the deck title and language", () => {
    expect(deck.title).toBe("Mini deck — fixture");
    expect(deck.lang).toBe("pt-BR");
  });

  it("captures viewport meta", () => {
    expect(deck.meta.viewport).toBe("width=device-width, initial-scale=1.0");
  });

  it("hoists every <style> block into theme_css", () => {
    expect(deck.theme_css).toContain(".slide { padding: 24px; }");
  });

  it("hoists every <script> block into nav_js", () => {
    expect(deck.nav_js).toContain('console.log("nav loaded")');
  });

  it("decomposes top-level <section class='slide'> into ordered slides", () => {
    expect(deck.slides).toHaveLength(3);
    expect(deck.slides.map((s) => s.position)).toEqual([0, 1, 2]);
  });

  it("derives slide titles from headings, eyebrow, or class modifiers", () => {
    expect(deck.slides[0].title).toBe("Cover");
    expect(deck.slides[1].title).toBe("Painéis");
    // Slide 3 has no heading; the eyebrow / class modifier picks up the slack.
    expect(deck.slides[2].title.length).toBeGreaterThan(0);
  });

  it("preserves class modifiers other than 'slide'", () => {
    expect(deck.slides[0].class_modifiers).toEqual(["cover-slide"]);
    expect(deck.slides[2].class_modifiers).toEqual(["blue-slide", "divider"]);
  });

  it("hoists base64 <img> data URLs into assets and rewrites src to placeholders", () => {
    expect(deck.assets).toHaveLength(1);
    expect(deck.assets[0].mime_type).toBe("image/png");
    expect(deck.assets[0].data.byteLength).toBeGreaterThan(0);
    expect(deck.slides[1].html_body).toContain(deck.assets[0].placeholder_id);
    expect(deck.slides[1].html_body).not.toContain("data:image/png;base64");
  });

  it("wraps slide html_body in a <section> with the original classes", () => {
    expect(deck.slides[0].html_body.startsWith('<section class="slide cover-slide">')).toBe(true);
    expect(deck.slides[0].html_body.endsWith("</section>")).toBe(true);
  });

  it("decodes HTML entities in extracted slide titles", () => {
    // We support the SGML standard names + numeric (&#nnn;, &#xhh;). Less
    // common named entities like &atilde; fall through unchanged — that's
    // documented in decodeEntities. Decks generated by Claude tend to use
    // either UTF-8 directly or the standard escape set.
    const sample = `<!DOCTYPE html><html><head><title>x</title></head><body>
      <section class="slide"><h1>Hub de FP&amp;A &amp; Comercial</h1></section>
      <section class="slide"><h2>Onde est&#227;o as &quot;dores&quot;?</h2></section>
      <section class="slide"><h1>&#233; aqui</h1></section>
    </body></html>`;
    const parsed = parseDeckHtml(sample);
    expect(parsed.slides[0].title).toBe("Hub de FP&A & Comercial");
    expect(parsed.slides[1].title).toBe('Onde estão as "dores"?');
    expect(parsed.slides[2].title).toBe("é aqui");
  });

  it("decodes HTML entities in the deck <title>, not only slide titles", () => {
    // Regression: the deck title was captured raw while slide titles were
    // decoded, so assembleDeckHtml's escapeHtml double-escaped it on export
    // (<title>Tom &amp; Jerry</title> rendered as the literal "Tom &amp; Jerry").
    const sample = `<!DOCTYPE html><html><head><title>Tom &amp; Jerry &quot;Q3&quot;</title></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    expect(parseDeckHtml(sample).title).toBe('Tom & Jerry "Q3"');
  });

  it("falls back to 'Untitled deck' when there is no <title>", () => {
    const sample = `<!DOCTYPE html><html><head></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    expect(parseDeckHtml(sample).title).toBe("Untitled deck");
  });
});

describe("parseDeckHtml — tolerant slide detection", () => {
  it("tier 2: decomposes <div class='slide'> inside a <div class='slides'> track", () => {
    // The shape a lot of Claude decks ship (a real client deck shipped exactly this) —
    // div-wrapped slides in a horizontal `.slides` strip. Used to parse to 0.
    const html = `<!DOCTYPE html><html lang="pt-BR"><head><title>Div deck</title>
      <style>.slide { padding: 24px; }</style></head><body>
      <div class="deck">
        <div class="top-nav"><div class="top-nav-section">Intro</div></div>
        <div class="slides" id="slides">
          <div class="slide"><div class="eyebrow">Diagnóstico</div><h1>Slide One</h1></div>
          <div class="slide"><h1>Slide Two</h1><div class="card">nested</div></div>
          <div class="slide cover"><h2>Slide Three</h2></div>
        </div>
      </div>
      <script>console.log("nav")</script></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides).toHaveLength(3);
    expect(deck.slides.map((s) => s.title)).toEqual(["Slide One", "Slide Two", "Slide Three"]);
    // Every slide is normalised to a <section class="slide …"> wrapper.
    expect(deck.slides[0].html_body.startsWith('<section class="slide">')).toBe(true);
    expect(deck.slides[2].html_body.startsWith('<section class="slide cover">')).toBe(true);
    expect(deck.slides[2].class_modifiers).toEqual(["cover"]);
    // The `.slides` container and `.top-nav` chrome are NOT slides.
    expect(deck.theme_css).toContain(".slide { padding: 24px; }");
    expect(deck.nav_js).toContain('console.log("nav")');
  });

  it("tier 2: a nested class='slide' badge doesn't split its parent slide", () => {
    const html = `<html><head><title>x</title></head><body>
      <div class="slides">
        <div class="slide"><h1>Only One</h1><span class="slide-pill">label</span>
          <div class="slide-note">inner note with the word slide</div></div>
      </div></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides).toHaveLength(1);
    expect(deck.slides[0].title).toBe("Only One");
  });

  it("tier 2: also accepts <article class='slide'>", () => {
    const html = `<html><head><title>x</title></head><body>
      <article class="slide"><h1>A</h1></article>
      <article class="slide"><h1>B</h1></article></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides.map((s) => s.title)).toEqual(["A", "B"]);
    expect(deck.slides[0].html_body.startsWith('<section class="slide">')).toBe(true);
  });

  it("tier 1 still wins when canonical <section class='slide'> exist", () => {
    // A deck with real sections must NOT also pick up a decorative .slide div.
    const html = `<html><head><title>x</title></head><body>
      <section class="slide"><h1>Real One</h1><div class="slide-thumb">deco</div></section>
      <section class="slide"><h1>Real Two</h1></section></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides.map((s) => s.title)).toEqual(["Real One", "Real Two"]);
  });

  it("tier 3: falls back to direct children of a #slides container when slides aren't class-marked", () => {
    const html = `<html><head><title>x</title></head><body>
      <div id="slides">
        <div class="panel"><h1>Page One</h1></div>
        <div class="panel"><h1>Page Two</h1></div>
      </div></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides.map((s) => s.title)).toEqual(["Page One", "Page Two"]);
    // Original class is preserved (its own CSS targets it); normalised to <section>.
    expect(deck.slides[0].html_body.startsWith('<section class="panel">')).toBe(true);
  });

  it("returns zero slides for HTML with no recognisable slide structure", () => {
    // The importer turns this into a loud `no_slides` error rather than a deck.
    const html = `<html><head><title>x</title></head><body>
      <main><h1>Just a page</h1><p>No slides here.</p></main></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.slides).toHaveLength(0);
  });
});

// Optional smoke-test against a real-world deck if present locally.
// This file is gitignored — the suite passes whether or not it exists.
const seedPath = join(fixturesDir, "seed-deck.html");
const hasSeed = existsSync(seedPath);

describe.runIf(hasSeed)("parseDeckHtml — real-world deck", () => {
  // Read inside beforeAll, NOT at collection time. describe.runIf skips the it()
  // blocks when the (gitignored) fixture is absent, but the describe callback body
  // still executes during collection — an eager readFileSync here ENOENTs in CI,
  // where the fixture never exists. beforeAll only runs for a non-skipped suite.
  let deck: ReturnType<typeof parseDeckHtml>;
  beforeAll(() => {
    deck = parseDeckHtml(readFileSync(seedPath, "utf-8"));
  });

  it("recovers all top-level slides from the seed file", () => {
    // The seed proposal has 13 top-level `<section class="slide">` blocks.
    // We don't pin the exact count here in case the file is regenerated; we
    // assert it produced a non-trivial slide deck.
    expect(deck.slides.length).toBeGreaterThanOrEqual(10);
    expect(deck.slides.length).toBeLessThanOrEqual(40);
  });

  it("captures the deck title", () => {
    expect(deck.title.trim().length).toBeGreaterThan(0);
  });

  it("hoists at least one image asset", () => {
    expect(deck.assets.length).toBeGreaterThan(0);
  });

  it("produces non-empty theme_css and nav_js", () => {
    expect(deck.theme_css.length).toBeGreaterThan(100);
    expect(deck.nav_js.length).toBeGreaterThan(0);
  });
});

// CSS-background data URLs must be hoisted into assets the same way <img>
// data URLs are — otherwise a cover photo baked into theme_css as
// `background-image:url(data:…)` (the fixed-px weekly-deck case) stays inline and is
// re-sent on every slide render. The importer then rewrites the placeholder.
describe("parseDeckHtml — CSS background data URLs", () => {
  // 1×1 transparent PNG.
  const PNG =
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
  const html = `<!DOCTYPE html><html lang="en"><head><title>BG deck</title>
    <style>.cover-bg{position:absolute;inset:0;background-image:url('${PNG}');}</style>
    </head><body><section class="slide cover"><div class="cover-bg"></div><h1>Cover</h1></section></body></html>`;
  const deck = parseDeckHtml(html);

  it("hoists the CSS background image into assets", () => {
    expect(deck.assets).toHaveLength(1);
    expect(deck.assets[0].mime_type).toBe("image/png");
    expect(deck.assets[0].data.byteLength).toBeGreaterThan(0);
  });

  it("rewrites the data URL in theme_css to a placeholder", () => {
    expect(deck.theme_css).not.toContain("data:image/png;base64");
    expect(deck.theme_css).toContain(deck.assets[0].placeholder_id);
    // The url() wrapper survives so the CSS stays valid.
    expect(deck.theme_css).toContain(`url("${deck.assets[0].placeholder_id}")`);
  });

  it("leaves a non-extractable CSS data URL (svg → active type) inline", () => {
    const svg = "data:image/svg+xml;base64,PHN2Zy8+";
    const h = `<html><head><title>t</title><style>.x{background:url(${svg})}</style></head><body><section class="slide"><h1>x</h1></section></body></html>`;
    const d = parseDeckHtml(h);
    expect(d.assets).toHaveLength(0);
    expect(d.theme_css).toContain(svg);
  });
});

// Embedded fonts ride the same extraction path as images. Regression for the
// 2026-07-11 prod import failures: a deck whose @font-face embeds a TTF data
// URL parsed fine, then the storage upload rejected `font/ttf` and the whole
// import died. The parser must lift the font AND emit the canonical mime
// spelling the `decks` bucket allows (migration 0077).
describe("parseDeckHtml — embedded font data URLs + mime canonicalization", () => {
  const TTF = `data:font/ttf;base64,${Buffer.from("fake-ttf-bytes").toString("base64")}`;
  const html = `<!DOCTYPE html><html lang="en"><head><title>Font deck</title>
    <style>@font-face{font-family:X;src:url('${TTF}') format('truetype');}</style>
    </head><body><section class="slide"><h1>Cover</h1></section></body></html>`;
  const deck = parseDeckHtml(html);

  it("hoists a TTF @font-face data URL into assets", () => {
    expect(deck.assets).toHaveLength(1);
    expect(deck.assets[0].mime_type).toBe("font/ttf");
    expect(deck.theme_css).not.toContain("data:font/ttf");
    expect(deck.theme_css).toContain(deck.assets[0].placeholder_id);
  });

  it("normalizes alias mimes onto the canonical spelling", () => {
    const woff = `data:application/font-woff;base64,${Buffer.from("fake-woff").toString("base64")}`;
    const jpg = `data:image/jpg;base64,${Buffer.from("fake-jpg").toString("base64")}`;
    const h = `<html><head><title>t</title><style>@font-face{src:url(${woff})}</style></head><body><section class="slide"><img src="${jpg}"><h1>x</h1></section></body></html>`;
    const d = parseDeckHtml(h);
    expect(d.assets.map((a) => a.mime_type).sort()).toEqual([
      "font/woff",
      "image/jpeg",
    ]);
  });

  it("ASSET_UPLOAD_MIMES carries canonical spellings only", () => {
    for (const alias of [
      "image/jpg",
      "image/vnd.microsoft.icon",
      "application/font-woff",
      "application/font-woff2",
    ]) {
      expect(ASSET_UPLOAD_MIMES).not.toContain(alias);
    }
    expect(ASSET_UPLOAD_MIMES).toContain("font/ttf");
    expect(ASSET_UPLOAD_MIMES).toContain("font/otf");
  });
});

describe("parseDeckHtml — non-slide body chrome (chrome_html)", () => {
  // Standalone/PPTX-style deck: slides live inside .stage-area > .viewport >
  // .track wrappers; the modal overlay + dots rail are body-level siblings the
  // nav_js drives via getElementById. Dropping them (the old behaviour) made
  // onclick="openModal(...)" slides dead in Canvas.
  const html = `<!DOCTYPE html>
<html lang="pt-BR">
<head><title>Interactive deck</title>
<style>.slide{width:1280px;height:720px}</style>
</head>
<body>
  <div class="stage-area">
    <div class="viewport" id="vp">
      <div class="track" id="track">
        <section class="slide"><h1>One</h1><div class="dor" onclick="openModal('d1')">Dor 1</div></section>
        <section class="slide"><h1>Two</h1></section>
      </div>
    </div>
    <div class="arrows"><button onclick="go(-1)">←</button><button onclick="go(1)">→</button></div>
  </div>
  <div class="dots" id="dots"></div>
  <div class="overlay" id="ov"><div class="modal" id="modalBox"></div></div>
  <script>function openModal(id){ document.getElementById('modalBox').innerHTML = id; document.getElementById('ov').classList.add('open'); }</script>
</body>
</html>`;
  const deck = parseDeckHtml(html);

  it("still extracts the slides", () => {
    expect(deck.slides).toHaveLength(2);
    expect(deck.slides[0].html_body).toContain("openModal('d1')");
  });

  it("preserves body-level chrome siblings (overlay, dots)", () => {
    expect(deck.chrome_html).toContain('id="ov"');
    expect(deck.chrome_html).toContain('id="modalBox"');
    expect(deck.chrome_html).toContain('id="dots"');
  });

  it("rescues chrome nested inside slide-bearing wrappers (arrows in .stage-area)", () => {
    expect(deck.chrome_html).toContain('class="arrows"');
  });

  it("drops the slide-bearing wrappers themselves and the slides", () => {
    expect(deck.chrome_html).not.toContain('id="vp"');
    expect(deck.chrome_html).not.toContain('id="track"');
    expect(deck.chrome_html).not.toContain("<section");
    expect(deck.chrome_html).not.toContain("Dor 1");
  });

  it("strips script/style blocks from kept chrome (already hoisted)", () => {
    expect(deck.chrome_html).not.toContain("<script");
  });

  it("is empty for a canonical Canvas-native deck", () => {
    const native = readFixture("mini-deck.html");
    const nativeDeck = parseDeckHtml(native);
    // The mini fixture may keep non-slide siblings; the invariant that matters:
    // no slide markup ever leaks into chrome_html.
    expect(nativeDeck.chrome_html).not.toContain("<section");
  });
});

// The parser used to discard the whole <head>, so a deck that pulled its font
// from a `<link rel="stylesheet" href="https://fonts.googleapis.com/...">` lost
// it the instant it entered Canvas and rendered in a fallback font. We now
// preserve allowlisted font links into meta.font_links; assemble re-emits them.
describe("parseDeckHtml — preserved web-font links (meta.font_links)", () => {
  it("captures a Google Fonts <link rel='stylesheet'> href into meta.font_links", () => {
    const href = "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap";
    const html = `<!DOCTYPE html><html lang="en"><head><title>Fonted deck</title>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link rel="stylesheet" href="${href}">
      <style>body{font-family:'Inter',sans-serif}</style></head>
      <body><section class="slide"><h1>Hi</h1></section></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.meta.font_links).toEqual([href]);
  });

  it("captures fonts.bunny.net and fonts.gstatic.com stylesheet links", () => {
    const bunny = "https://fonts.bunny.net/css?family=inter:400,700";
    const gstatic = "https://fonts.gstatic.com/custom/fonts.css";
    const html = `<html><head><title>x</title>
      <link rel="stylesheet" href="${bunny}">
      <link rel="stylesheet" href="${gstatic}"></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.meta.font_links).toEqual([bunny, gstatic]);
  });

  it("does NOT capture a non-font <link> (CDN stylesheet) or non-stylesheet rels", () => {
    const html = `<html><head><title>x</title>
      <link rel="stylesheet" href="https://cdn.example.com/app.css">
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="icon" href="https://fonts.gstatic.com/favicon.ico"></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    const deck = parseDeckHtml(html);
    // Off-allowlist host is dropped; allowlisted-but-not-stylesheet rels too.
    expect(deck.meta.font_links).toBeUndefined();
  });

  it("dedupes a repeated font link and tolerates single quotes", () => {
    const href = "https://fonts.googleapis.com/css2?family=Roboto";
    const html = `<html><head><title>x</title>
      <link rel='stylesheet' href='${href}'>
      <link rel="stylesheet" href="${href}"></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    const deck = parseDeckHtml(html);
    expect(deck.meta.font_links).toEqual([href]);
  });

  it("omits meta.font_links entirely when the deck has no font links", () => {
    const html = `<html><head><title>x</title></head>
      <body><section class="slide"><h1>x</h1></section></body></html>`;
    expect(parseDeckHtml(html).meta.font_links).toBeUndefined();
  });
});

describe("isAllowlistedFontUrl", () => {
  it("accepts the known font hosts and their subdomains", () => {
    expect(isAllowlistedFontUrl("https://fonts.googleapis.com/css2?family=Inter")).toBe(true);
    expect(isAllowlistedFontUrl("https://fonts.gstatic.com/s/inter/x.woff2")).toBe(true);
    expect(isAllowlistedFontUrl("https://fonts.bunny.net/css?family=inter")).toBe(true);
    // Subdomain of an allowlisted host.
    expect(isAllowlistedFontUrl("https://cdn.fonts.gstatic.com/x.woff2")).toBe(true);
  });

  it("rejects off-allowlist hosts, lookalikes, and malformed URLs", () => {
    expect(isAllowlistedFontUrl("https://evil.com/x.woff2")).toBe(false);
    // A suffix attack: notfonts.googleapis.com must NOT match googleapis.com.
    expect(isAllowlistedFontUrl("https://fonts.googleapis.com.evil.com/x")).toBe(false);
    expect(isAllowlistedFontUrl("not a url")).toBe(false);
    expect(isAllowlistedFontUrl("/relative/path.css")).toBe(false);
  });
});
